name: QA-Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - run: python main.py 10 + 5
    - run: python main.py 10 x 5
    - run: python main.py 10 - 5
    - run: python main.py 10 / 5


            
            